### ISSUE TITLE
Crashing on prediction from peptide list

### ISSUE THREAD

**Issue by tretyacv** [MannLabs/alphapeptdeep#107]
**Describe the bug**
Hi, GUI interface outputs an error when submitting a job from sequence_table:

```
2023-08-24 09:41:14> Downloading pretrained_models.zip ...
2023-08-24 09:41:16> The pretrained models had been downloaded in C:\Users\slavat.WISMAIN/peptdeep\pretrained_models\pretrained_models.zip
Starting PeptDeep Web Server on port 10077 ...

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:10077
  Network URL: http://132.77.89.166:10077

*********************************
[PeptDeep] Waiting for tasks ...
*********************************
[PeptDeep] Starting a new job 'C:\Users\slavat.WISMAIN/peptdeep/tasks/queue\peptdeep_library_2023-08-24--11-03-00.912749.yaml'...
[PeptDeep] Predicting library ...
2023-08-24 11:03:01> Platform information:
2023-08-24 11:03:01> system        - Windows
2023-08-24 11:03:01> release       - 10
2023-08-24 11:03:01> version       - 10.0.19044
2023-08-24 11:03:01> machine       - AMD64
2023-08-24 11:03:01> processor     - AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD
2023-08-24 11:03:01> cpu count     - 16
2023-08-24 11:03:01> ram           - 23.5/31.4 Gb (available/total)
2023-08-24 11:03:01>
2023-08-24 11:03:01> Python information:
2023-08-24 11:03:01> alphabase        - 1.0.2
2023-08-24 11:03:01> biopython        - 1.81
2023-08-24 11:03:01> click            - 8.1.3
2023-08-24 11:03:01> lxml             - 4.9.2
2023-08-24 11:03:01> numba            - 0.56.4
2023-08-24 11:03:01> numpy            - 1.23.5
2023-08-24 11:03:01> pandas           - 1.5.3
2023-08-24 11:03:01> peptdeep         - 1.0.2
2023-08-24 11:03:01> psutil           - 5.9.4
2023-08-24 11:03:01> python           - 3.9.16
2023-08-24 11:03:01> scikit-learn     - 1.2.1
2023-08-24 11:03:01> streamlit        - 1.19.0
2023-08-24 11:03:01> streamlit-aggrid - 0.3.3
2023-08-24 11:03:01> torch            - 1.13.1
2023-08-24 11:03:01> tqdm             - 4.64.1
2023-08-24 11:03:01> transformers     - 4.26.1
2023-08-24 11:03:01>
2023-08-24 11:03:05> Generating the spectral library ...
2023-08-24 11:03:05> Traceback (most recent call last):
  File "peptdeep\pipeline_api.py", line 308, in generate_library
    lib_maker.make_library(df)
  File "peptdeep\spec_lib\library_factory.py", line 101, in make_library
    self._input(_input)
  File "peptdeep\spec_lib\library_factory.py", line 210, in _input
    self.spec_lib.append_decoy_sequence()
  File "alphabase\spectral_library\base.py", line 166, in append_decoy_sequence
    decoy_lib.decoy_sequence()
  File "alphabase\spectral_library\decoy.py", line 65, in decoy_sequence
    self._decoy_seq()
  File "alphabase\spectral_library\decoy.py", line 74, in _decoy_seq
    ) = self._precursor_df.sequence.apply(
  File "pandas\core\generic.py", line 5902, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'sequence'

'DataFrame' object has no attribute 'sequence'
``` 

**To Reproduce**
1. Start GUI
2. Put a sequence_table (attached) in the library
3. Keep everything else default and submit

[peptide_list.txt](https://github.com/MannLabs/alphapeptdee
[peptide_list.zip](https://github.com/MannLabs/alphapeptdeep/files/12427136/peptide_list.zip)
p/files/12427127/peptide_list.txt)

**Comment by tretyacv** [comment]
solved, the input file needs to have a header
