### ISSUE TITLE
Peptdeep GUI error in new version

### ISSUE THREAD

**Issue by Maithy15** [MannLabs/alphapeptdeep#114]
Hi,

When I try to start a GUI from CLI, I get the following error. Could you please tell me what is wrong here?

Thanks
Maithy

Here is the error

(peptdeep) C:\Users\m284y>peptdeep gui

     ____             __  ____
    / __ \___  ____  / /_/ __ \___  ___  ____
   / /_/ / _ \/ __ \/ __/ / / / _ \/ _ \/ __ \
  / ____/  __/ /_/ / /_/ /_/ /  __/  __/ /_/ /
 /_/    \___/ .___/\__/_____/\___/\___/ .___/
           /_/                       /_/
....................................................
.                      1.1.0                       .
.       https://github.com/MannLabs/peptdeep       .
.                    Apache 2.0                    .
....................................................

Traceback (most recent call last):
  File "C:\Users\m284y\.conda\envs\peptdeep\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\m284y\.conda\envs\peptdeep\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\m284y\.conda\envs\peptdeep\Scripts\peptdeep.exe\__main__.py", line 7, in <module>
  File "C:\Users\m284y\.conda\envs\peptdeep\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\m284y\.conda\envs\peptdeep\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\m284y\.conda\envs\peptdeep\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\m284y\.conda\envs\peptdeep\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\m284y\.conda\envs\peptdeep\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\m284y\.conda\envs\peptdeep\lib\site-packages\peptdeep\cli.py", line 56, in _gui
    from peptdeep.webui.server import _server
  File "C:\Users\m284y\.conda\envs\peptdeep\lib\site-packages\peptdeep\webui\server.py", line 7, in <module>
    from peptdeep.pipeline_api import (
ImportError: cannot import name 'rescore' from 'peptdeep.pipeline_api' (C:\Users\m284y\.conda\envs\peptdeep\lib\site-packages\peptdeep\pipeline_api.py)

**Comment by jalew188** [comment]
Did you use the installer or `pip install peptdeep`? Anyway, there is indeed bug as I removed rescore module from the 2.1.0 but peptdeep gui still calls it.

**Comment by jalew188** [comment]
@Maithy15 I am developing a new GUI that uses the new CLI `peptdeep cmd-flow ...` (https://github.com/MannLabs/alphapeptdeep#cmd-flow) to address other issues in the old GUI runner. 

If you are using git to fetch alphapeptdeep, I can quickly update the code in the next days.

**Comment by Maithy15** [comment]
Hi,

Thanks for the quick reply. I used the pip installer. I cannot find windows installer for the latest version of GUI.

Thanks
Maithy

**Comment by jalew188** [comment]
@Maithy15 Too busy in this month, I am working on this now

**Comment by Maithy15** [comment]
Thanks for the update!

**Comment by jalew188** [comment]
@Maithy15 Windows installer (v1.1.1) has been updated
