### ISSUE TITLE
Value error + Peptdeep is trying to use multiprocess even when it is not selected

### ISSUE THREAD

**Issue by Maithy15** [MannLabs/alphapeptdeep#123]
Hi,

Thanks for the latest update.

I am trying it but it seems to get stuck at one point with no output. I have the log pasted here. Additionally I have uploaded the settings file. Please et me know if there is any mistake in the setting.

[peptdeep_library_2023-12-29--10-08-25.862954.yaml.zip](https://github.com/MannLabs/alphapeptdeep/files/13792668/peptdeep_library_2023-12-29--10-08-25.862954.yaml.zip)

Starting PeptDeep Web Server on port 10077 ...

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:10077
  Network URL: http://193.174.62.4:10077

[PeptDeep] Starting a new job 'C:\Users\m284y/peptdeep/tasks/queue\peptdeep_library_2023-10-05--19-40-40.124913.yaml'...[PeptDeep] Predicting library ...
2023-12-29 10:07:32> [PeptDeep] Running library task ...
2023-12-29 10:07:32> Input files (fasta): ['E:/FASTA/HUMAN_070321/7March21_uniprot-proteome_UP000005640+reviewed_yes.fasta']
2023-12-29 10:07:32> Platform information:
2023-12-29 10:07:32> system        - Windows
2023-12-29 10:07:32> release       - 10
2023-12-29 10:07:32> version       - 10.0.19045
2023-12-29 10:07:32> machine       - AMD64
2023-12-29 10:07:32> processor     - AMD64 Family 23 Model 49 Stepping 0, AuthenticAMD
2023-12-29 10:07:32> cpu count     - 128
2023-12-29 10:07:32> ram           - 234.3/255.9 Gb (available/total)
2023-12-29 10:07:32>
2023-12-29 10:07:32> Python information:
2023-12-29 10:07:32> alphabase        - 1.2.0
2023-12-29 10:07:32> alpharaw         - 0.4.0
2023-12-29 10:07:32> biopython        -
2023-12-29 10:07:32> click            - 8.1.7
2023-12-29 10:07:32> lxml             - 4.9.4
2023-12-29 10:07:32> numba            - 0.58.1
2023-12-29 10:07:32> numpy            - 1.26.2
2023-12-29 10:07:32> pandas           - 2.1.4
2023-12-29 10:07:32> peptdeep         - 1.1.1
2023-12-29 10:07:32> psutil           - 5.9.7
2023-12-29 10:07:32> pyteomics        - 4.6.3
2023-12-29 10:07:32> python           - 3.9.18
2023-12-29 10:07:32> scikit-learn     - 1.3.2
2023-12-29 10:07:32> streamlit        - 1.29.0
2023-12-29 10:07:32> streamlit-aggrid -
2023-12-29 10:07:32> torch            - 2.1.2
2023-12-29 10:07:32> tqdm             - 4.66.1
2023-12-29 10:07:32> transformers     - 4.36.2
2023-12-29 10:07:32>
2023-12-29 10:07:34> xxx/library.tsv does not exist, use default IRT_PEPTIDE_DF to translate irt
2023-12-29 10:07:34> Generating the spectral library ...
2023-12-29 10:11:37> Loaded 23643549 precursors.
2023-12-29 10:13:50> Predicting RT/IM/MS2 for 19882736 precursors ...
2023-12-29 10:13:50> Using multiprocessing with 100 processes ...
2023-12-29 10:13:50> Predicting rt,mobility,ms2 ...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 980, in _bootstrap_inner
  File "threading.py", line 917, in run
  File "multiprocessing\pool.py", line 519, in _handle_workers
  File "multiprocessing\pool.py", line 499, in _wait_for_updates
  File "multiprocessing\connection.py", line 879, in wait
  File "multiprocessing\connection.py", line 811, in _exhaustive_wait
ValueError: need at most 63 handles, got a sequence of length 102
 47%|████████████████████████████████████████████████████████▍                                                              | 101/213 [1:11:24<1:31:48, 49.18s/it]

**Comment by Maithy15** [comment]
Just give you an update, I tried it one another computer and it working fine

2023-12-29 12:01:14> Downloading pretrained_models.zip ...
2023-12-29 12:01:17> The pretrained models had been downloaded in C:\Users\m284y/peptdeep\pretrained_models\pretrained_models.zip
Starting PeptDeep Web Server on port 10077 ...

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:10077
  Network URL: http://172.22.62.33:10077

*********************************
[PeptDeep] Waiting for tasks ...
*********************************
[PeptDeep] Starting a new job 'C:\Users\m284y/peptdeep/tasks/queue\peptdeep_library_2023-12-29--12-05-00.476766.yaml'...[PeptDeep] Predicting library ...
2023-12-29 12:05:02> [PeptDeep] Running library task ...
2023-12-29 12:05:02> Input files (fasta): ['D:/FASTA/Fasta_2021_Copy/HUMAN_070321/7March21_uniprot-proteomeUP000005640+reviewed_yes.fasta']
2023-12-29 12:05:02> Platform information:
2023-12-29 12:05:02> system        - Windows
2023-12-29 12:05:02> release       - 10
2023-12-29 12:05:02> version       - 10.0.19045
2023-12-29 12:05:02> machine       - AMD64
2023-12-29 12:05:02> processor     - AMD64 Family 25 Model 8 Stepping 2, AuthenticAMD
2023-12-29 12:05:02> cpu count     - 64
2023-12-29 12:05:02> ram           - 119.2/127.8 Gb (available/total)
2023-12-29 12:05:02>
2023-12-29 12:05:02> Python information:
2023-12-29 12:05:02> alphabase        - 1.2.0
2023-12-29 12:05:02> alpharaw         - 0.4.0
2023-12-29 12:05:02> biopython        -
2023-12-29 12:05:02> click            - 8.1.7
2023-12-29 12:05:02> lxml             - 4.9.4
2023-12-29 12:05:02> numba            - 0.58.1
2023-12-29 12:05:02> numpy            - 1.26.2
2023-12-29 12:05:02> pandas           - 2.1.4
2023-12-29 12:05:02> peptdeep         - 1.1.1
2023-12-29 12:05:02> psutil           - 5.9.7
2023-12-29 12:05:02> pyteomics        - 4.6.3
2023-12-29 12:05:02> python           - 3.9.18
2023-12-29 12:05:02> scikit-learn     - 1.3.2
2023-12-29 12:05:02> streamlit        - 1.29.0
2023-12-29 12:05:02> streamlit-aggrid -
2023-12-29 12:05:02> torch            - 2.1.2
2023-12-29 12:05:02> tqdm             - 4.66.1
2023-12-29 12:05:02> transformers     - 4.36.2
2023-12-29 12:05:02>
2023-12-29 12:05:04> xxx/library.tsv does not exist, use default IRT_PEPTIDE_DF to translate irt
2023-12-29 12:05:04> Generating the spectral library ...
2023-12-29 12:11:00> Loaded 41331786 precursors.
2023-12-29 12:14:02> Predicting RT/IM/MS2 for 38231621 precursors ...
2023-12-29 12:14:03> Predicting RT ...
 28%|████████████████████████████▋                                                                           | 8/29 [20:08<1:03:23, 181.12s/it]

**Comment by jalew188** [comment]
Hi @Maithy15, Python only allows maximal number of 64 threads:

`ValueError: need at most 63 handles, got a sequence of length 102`
