### ISSUE TITLE
Error: '_Pseudo_Bert_Config' object has no attribute '_attn_implementation'

### ISSUE THREAD

**Issue by mschwoer** [MannLabs/alphapeptdeep#172]
**Describe the bug**
The 'astral' test in alphadia fails with
```
0:00:00.025385 PROGRESS: No library provided. Building library from fasta files.
0:00:00.025425 INFO: Running FastaDigest
0:00:00.029088 INFO: Traceback (most recent call last):
  File "/home/runner/_work/alphadia/alphadia/alphadia/cli.py", line 349, in run
    plan = Plan(
  File "/home/runner/_work/alphadia/alphadia/alphadia/planning.py", line 108, in __init__
    self.load_library()
  File "/home/runner/_work/alphadia/alphadia/alphadia/planning.py", line 179, in load_library
    spectral_library = fasta_digest(self.fasta_path_list)
  File "/home/runner/_work/alphadia/alphadia/alphadia/libtransform.py", line 40, in __call__
    return self.forward(*args)
  File "/home/runner/_work/alphadia/alphadia/alphadia/libtransform.py", line 176, in forward
    model_mgr = ModelManager()
  File "/home/runner/.conda/envs/alphadia-87af67c6f71105445c7aa8efa9349d8aad6d9759-9192270161-1/lib/python3.9/site-packages/peptdeep/pretrained_models.py", line 300, in __init__
    self.ms2_model:pDeepModel = pDeepModel(mask_modloss=mask_modloss, device=device)
  File "/home/runner/.conda/envs/alphadia-87af67c6f71105445c7aa8efa9349d8aad6d9759-9192270161-1/lib/python3.9/site-packages/peptdeep/model/ms2.py", line 385, in __init__
    self.build(
  File "/home/runner/.conda/envs/alphadia-87af67c6f71105445c7aa8efa9349d8aad6d9759-9192270161-1/lib/python3.9/site-packages/peptdeep/model/model_interface.py", line 248, in build
    self.model = model_class(**kwargs)
  File "/home/runner/.conda/envs/alphadia-87af67c6f71105445c7aa8efa9349d8aad6d9759-9192270161-1/lib/python3.9/site-packages/peptdeep/model/ms2.py", line 171, in __init__
    self.hidden_nn = building_block.Hidden_HFace_Transformer(
  File "/home/runner/.conda/envs/alphadia-87af67c6f71105445c7aa8efa9349d8aad6d9759-9192270161-1/lib/python3.9/site-packages/peptdeep/model/building_block.py", line 224, in __init__
    self.bert = BertEncoder(self.config)
  File "/home/runner/.conda/envs/alphadia-87af67c6f71105445c7aa8efa9349d8aad6d9759-9192270161-1/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 643, in __init__
    self.layer = nn.ModuleList([BertLayer(config) for _ in range(config.num_hidden_layers)])
  File "/home/runner/.conda/envs/alphadia-87af67c6f71105445c7aa8efa9349d8aad6d9759-9192270161-1/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 643, in <listcomp>
    self.layer = nn.ModuleList([BertLayer(config) for _ in range(config.num_hidden_layers)])
  File "/home/runner/.conda/envs/alphadia-87af67c6f71105445c7aa8efa9349d8aad6d9759-9192270161-1/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 558, in __init__
    self.attention = BertAttention(config)
  File "/home/runner/.conda/envs/alphadia-87af67c6f71105445c7aa8efa9349d8aad6d9759-9192270161-1/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 476, in __init__
    self.self = BERT_SELF_ATTENTION_CLASSES[config._attn_implementation](
AttributeError: '_Pseudo_Bert_Config' object has no attribute '_attn_implementation'

0:00:00.029172 ERROR: '_Pseudo_Bert_Config' object has no attribute '_attn_implementation'

```

**To Reproduce**
Run this test: https://github.com/MannLabs/alphadia/actions/runs/9192270161/job/25280516976

`./run_e2e_tests.sh astral`

**Expected behavior**
No exception

**Comment by jalew188** [comment]
Fixed in https://github.com/MannLabs/alphapeptdeep/issues/168
