### ISSUE TITLE
Error while trying to create library

### ISSUE THREAD

**Issue by nurudeen95** [MannLabs/alphapeptdeep#176]
**I am really new to using alphapeptdeep. I wanted to generate a predicted library for some sequences using the GUI. The list contains 1755 sequences. **

**To Reproduce**
Since this is my first time using alphapeptdeep, I tried to keep things simple and leave all the settings as is. However, I got this error some minutes into the run:

**Logs**
Traceback (most recent call last):
  File "multiprocessing\pool.py", line 125, in worker
  File "peptdeep\pretrained_models.py", line 936, in _predict_func_for_mp
    return self.predict_all(
  File "peptdeep\pretrained_models.py", line 1130, in predict_all
    fragment_intensity_df = self.predict_ms2(
  File "peptdeep\pretrained_models.py", line 870, in predict_ms2
    return self.ms2_model.predict(precursor_df,
  File "peptdeep\model\ms2.py", line 582, in predict
    return super().predict(
  File "peptdeep\model\model_interface.py", line 543, in predict
    features = self._get_features_from_batch_df(
  File "peptdeep\model\ms2.py", line 444, in _get_features_from_batch_df
    mod_x = self._get_mod_features(batch_df)
  File "peptdeep\model\model_interface.py", line 967, in _get_mod_features
    get_batch_mod_feature(batch_df)
  File "peptdeep\model\featurize.py", line 75, in get_batch_mod_feature
    mod_x_batch = np.zeros(
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 2.35 MiB for an array with shape (166, 17, 109) and data type float64
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "peptdeep\pipeline_api.py", line 428, in generate_library
    lib_maker.make_library(lib_settings["infiles"])
  File "peptdeep\spec_lib\library_factory.py", line 105, in make_library
    self._predict()
  File "peptdeep\spec_lib\library_factory.py", line 68, in _predict
    self.spec_lib.predict_all()
  File "peptdeep\spec_lib\predict_lib.py", line 123, in predict_all
    res = self.model_manager.predict_all(
  File "peptdeep\pretrained_models.py", line 1155, in predict_all
    return self.predict_all_mp(
  File "peptdeep\pretrained_models.py", line 991, in predict_all_mp
    for ret_dict in process_bar(
  File "peptdeep\utils\__init__.py", line 18, in process_bar
    for i,iter in enumerate(iterator):
  File "multiprocessing\pool.py", line 870, in next
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 2.35 MiB for an array with shape (166, 17, 109) and data type float64

**Expected Result**
It seems like there is a memory issue but I wanted to be sure before I troubleshoot further.

**Version (please complete the following information):**
 GUI: Version 1.2.1

**Comment by jalew188** [comment]
Yes, it looks like a memory issue

**Comment by nurudeen95** [comment]
Alright. Thank you for the response. Are there recommended specification to run the GUI on?

**Comment by jalew188** [comment]
Try less process number or less batch size in GUI
