### ISSUE TITLE
GUI failed when cpu count < global_settings['thread_num']

### ISSUE THREAD

**Issue by jalew188** [MannLabs/alphapeptdeep#62]
```
Traceback (most recent call last):

  File "streamlit\runtime\scriptrunner\script_runner.py", line 556, in _run_script

    exec(code, module.__dict__)

  File "C:\Users\marth\AppData\Local\Programs\peptdeep\peptdeep\webui\main_ui.py", line 55, in <module>

    sidebar[menu]()

  File "peptdeep\webui\settings_ui.py", line 31, in show

    thread_num = st.number_input('Thread number',

  File "streamlit\elements\number_input.py", line 113, in number_input

    return self._number_input(

  File "streamlit\elements\number_input.py", line 225, in _number_input

    raise StreamlitAPIException(

streamlit.errors.StreamlitAPIException: The default `value` of 8 must lie between the `min_value` of None and the `max_value` of 4, inclusively.
```

**Comment by jalew188** [comment]
We have fixed this bug on github and on github release v0.2.0 (https://github.com/MannLabs/alphapeptdeep/releases/tag/0.2.0), 
but peptdeep v0.2.0 still has this bug on PyPi. It will be fixed on PyPi with peptideep v0.2.1
